### ISSUE TITLE
MATLAB code?

### ISSUE THREAD

**Issue by pgleeson** [MRIO/oliveML#2]
@MRIO can I check, was this model originally in Matlab?

Would it be possible to add that code to the repo too? Thanks!

**Comment by MRIO** [comment]
The model was originally in c, then I ported it to matlab and gpu’d it, and yes, I am happy to add the matlab model to the repo. We have two papers near submission, both using the model, so this is a good time. 

Incidentally, the student that was working on the parameter space analysis comparing the two models could not continue for personal reasons, so I may take that up sooner than later myself. Thus, the new model is not completely cross-validated yet.

I’ll upload the matlab soon,

Cheers!

Mario.

**Comment by pgleeson** [comment]
Thanks @MRIO!

**Comment by MRIO** [comment]
In the master branch I have now added the full fledged model (also with analysis tools and the like), though a nice readme and an even nicer tech report is still in the making. Their release is scheduled to co-occur with the publication of the first papers using the model. Sooner than later, we'd hope!
